--------------------------------------------------------
--  File created - Tuesday-October-25-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENT" 
   (	"REFFERENCENO" VARCHAR2(50 BYTE), 
	"CLIENTNAME" VARCHAR2(50 BYTE), 
	"HOMENO" VARCHAR2(50 BYTE), 
	"STREET" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LAWYER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LAWYER" 
   (	"LAWYERNAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESTATE_AGENCY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ESTATE_AGENCY" 
   (	"NAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROPERTY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PROPERTY" 
   (	"PROPERTY_ADDRESS" VARCHAR2(50 BYTE), 
	"REFFERENCENO" VARCHAR2(50 BYTE), 
	"ROOMTYPE" VARCHAR2(50 BYTE), 
	"NOOFROOMS" NUMBER(*,0), 
	"STATUSOFSALE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROPERTYVISIT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PROPERTYVISIT" 
   (	"PROPERTY_ADDRESS" VARCHAR2(50 BYTE), 
	"REFFERENCENO" VARCHAR2(50 BYTE), 
	"DATEOFVISIT" DATE DEFAULT SYSDATE, 
	"VISITORSTATUS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CLIENT
SET DEFINE OFF;
Insert into SYSTEM.CLIENT (REFFERENCENO,CLIENTNAME,HOMENO,STREET,STATUS) values ('cl_4','brian kgogwe','9945','9945','none');
Insert into SYSTEM.CLIENT (REFFERENCENO,CLIENTNAME,HOMENO,STREET,STATUS) values ('cl_5','faith kgogwe','4478','4478','none');
Insert into SYSTEM.CLIENT (REFFERENCENO,CLIENTNAME,HOMENO,STREET,STATUS) values ('cl_6','Tiger John','5536','5536','Purchaser');
Insert into SYSTEM.CLIENT (REFFERENCENO,CLIENTNAME,HOMENO,STREET,STATUS) values ('cl_7','Brian Sting','7721','7721','Seller');
Insert into SYSTEM.CLIENT (REFFERENCENO,CLIENTNAME,HOMENO,STREET,STATUS) values ('kl0',null,'5','5','sold');
Insert into SYSTEM.CLIENT (REFFERENCENO,CLIENTNAME,HOMENO,STREET,STATUS) values ('ew',null,'4','4','sold');
Insert into SYSTEM.CLIENT (REFFERENCENO,CLIENTNAME,HOMENO,STREET,STATUS) values ('cl_8','Susan may','4326','4326','Seller');
REM INSERTING into SYSTEM.LAWYER
SET DEFINE OFF;
REM INSERTING into SYSTEM.ESTATE_AGENCY
SET DEFINE OFF;
REM INSERTING into SYSTEM.PROPERTY
SET DEFINE OFF;
Insert into SYSTEM.PROPERTY (PROPERTY_ADDRESS,REFFERENCENO,ROOMTYPE,NOOFROOMS,STATUSOFSALE) values ('Morojwa, plot 4456','cl_7','3',3,'for sale');
Insert into SYSTEM.PROPERTY (PROPERTY_ADDRESS,REFFERENCENO,ROOMTYPE,NOOFROOMS,STATUSOFSALE) values ('Tlokweng, wood 1925','cl_8','4',4,'sold');
REM INSERTING into SYSTEM.PROPERTYVISIT
SET DEFINE OFF;
Insert into SYSTEM.PROPERTYVISIT (PROPERTY_ADDRESS,REFFERENCENO,DATEOFVISIT,VISITORSTATUS) values ('Morojwa, plot 4456','cl_8',to_date('23-OCT-22','DD-MON-RR'),'Interested');
Insert into SYSTEM.PROPERTYVISIT (PROPERTY_ADDRESS,REFFERENCENO,DATEOFVISIT,VISITORSTATUS) values ('Morojwa, plot 4456','cl_8',to_date('23-OCT-22','DD-MON-RR'),'Interested');
--------------------------------------------------------
--  DDL for Index SYS_C007083
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007083" ON "SYSTEM"."CLIENT" ("REFFERENCENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007080
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007080" ON "SYSTEM"."LAWYER" ("LAWYERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007081
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007081" ON "SYSTEM"."ESTATE_AGENCY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007129
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007129" ON "SYSTEM"."PROPERTY" ("PROPERTY_ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007139
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007139" ON "SYSTEM"."PROPERTYVISIT" ("PROPERTY_ADDRESS", "REFFERENCENO", "DATEOFVISIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENT" ADD PRIMARY KEY ("REFFERENCENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LAWYER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LAWYER" ADD PRIMARY KEY ("LAWYERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTATE_AGENCY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESTATE_AGENCY" ADD PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROPERTY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PROPERTY" ADD CONSTRAINT "CHECK_SALESTATUS" CHECK (statusofsale IN ('sold','for sale')) ENABLE;
  ALTER TABLE "SYSTEM"."PROPERTY" ADD PRIMARY KEY ("PROPERTY_ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROPERTYVISIT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PROPERTYVISIT" ADD PRIMARY KEY ("PROPERTY_ADDRESS", "REFFERENCENO", "DATEOFVISIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROPERTY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PROPERTY" ADD FOREIGN KEY ("REFFERENCENO")
	  REFERENCES "SYSTEM"."CLIENT" ("REFFERENCENO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROPERTYVISIT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PROPERTYVISIT" ADD FOREIGN KEY ("PROPERTY_ADDRESS")
	  REFERENCES "SYSTEM"."PROPERTY" ("PROPERTY_ADDRESS") ENABLE;
  ALTER TABLE "SYSTEM"."PROPERTYVISIT" ADD FOREIGN KEY ("REFFERENCENO")
	  REFERENCES "SYSTEM"."CLIENT" ("REFFERENCENO") ENABLE;
